 2 A

In [1]:
import numpy as np

print("NumPy Version:", np.__version__)

arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_0d = np.array(42)
arr_ones = np.ones((3, 3))

print("1D Array:")
print(arr_1d)

print("2D Array:")
print(arr_2d)

print("0D Array:")
print(arr_0d)

print("Array of Ones:")
print(arr_ones)

print("Element at index 2 in 1D array:", arr_1d[2])
print("Element at row 1, column 2 in 2D array:", arr_2d[1, 2])
print("Slice from 1D array:", arr_1d[1:4])
print("Slice row 1 from 2D array:", arr_2d[1, :])

arr_a = np.array([10, 20, 30])
arr_b = np.array([1, 2, 3])

print("Addition:", arr_a + arr_b)
print("Subtraction:", arr_a - arr_b)
print("Multiplication:", arr_a * arr_b)
print("Division:", arr_a / arr_b)
print("Scalar Multiplication:", arr_a * 2)

print("Sum:", np.sum(arr_a))
print("Mean:", np.mean(arr_a))
print("Standard Deviation:", np.std(arr_a))

print("Element-wise Comparison:", arr_a > arr_b)
print("Elements Greater Than 15:", arr_a[arr_a > 15])

indices = [0, 2]
print("Selected Elements:", arr_a[indices])

reshaped_arr = arr_1d.reshape(5, 1)
print("Reshaped Array:")
print(reshaped_arr)

structured_arr = np.array(
    [(25, 90.5), (30, 85.2)],
    dtype=[('age', 'i4'), ('score', 'f4')]
)

print("Structured Array:")
print(structured_arr)

print("Ages:", structured_arr['age'])
print("Scores:", structured_arr['score'])

NumPy Version: 2.0.2
1D Array:
[1 2 3 4 5]
2D Array:
[[1 2 3]
 [4 5 6]]
0D Array:
42
Array of Ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Element at index 2 in 1D array: 3
Element at row 1, column 2 in 2D array: 6
Slice from 1D array: [2 3 4]
Slice row 1 from 2D array: [4 5 6]
Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]
Scalar Multiplication: [20 40 60]
Sum: 60
Mean: 20.0
Standard Deviation: 8.16496580927726
Element-wise Comparison: [ True  True  True]
Elements Greater Than 15: [20 30]
Selected Elements: [10 30]
Reshaped Array:
[[1]
 [2]
 [3]
 [4]
 [5]]
Structured Array:
[(25, 90.5) (30, 85.2)]
Ages: [25 30]
Scores: [90.5 85.2]
